# Generated by Django 3.1 on 2020-08-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cal_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.IntegerField(max_length=10, verbose_name='year')),
                ('m', models.IntegerField(max_length=10, verbose_name='month')),
            ],
        ),
    ]
