# Generated by Django 3.1 on 2020-08-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal_table',
            name='m',
            field=models.IntegerField(verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='cal_table',
            name='y',
            field=models.IntegerField(verbose_name='year'),
        ),
    ]
